services:
  - type: web
    name: ssplp-backend
    env: node
    region: oregon
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    repository: https://github.com/Jongkuch1/ssplp-platform
    root: backend
